title: "Leo Laksmana"
description: "Senior Director of Engineering · Engineering Transformation Leader · AI Practitioner"

url: "https://beol.github.io"
repository: "beol/beol.github.io"

gravatar: 6f883e6660c16d8c1b51277eb4f602f1
linkedin: llaksmana

author:
  name: Leo Laksmana
  linkedin: llaksmana

social:
  name: Leo Laksmana
  links:
    - https://www.linkedin.com/in/llaksmana
    - https://github.com/beol

theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  [
    ".rvmrc",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "build.js",
    "vendor",
    "script",
  ]
