title: "Rants &amp; Raves"
description: ""

url: "http://beol.github.io"
repository: "beol/beol.github.io"

google_analytics: UA-8853012-4
quantcast: p-2hmv506hLezgG

theme: jekyll-theme-minimal

exclude: [".rvmrc", "README.md", "Gemfile", "Gemfile.lock", "build.js", "vendor", "script"]
