title: "Rants &amp; Raves"
description: "Systems engineer with running and triathlon aspirations"

url: "http://beol.github.io"
repository: "beol/beol.github.io"

google_analytics: UA-8853012-4
quantcast: p-2hmv506hLezgG
gravatar: 6f883e6660c16d8c1b51277eb4f602f1

theme: jekyll-theme-minimal
plugins:
    - jekyll-sitemap

exclude: [".rvmrc", "README.md", "Gemfile", "Gemfile.lock", "build.js", "vendor", "script"]
